@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwZDVkM2U4LTNiMTYtNDhmYS05ZTJlLTk4MzI5NDJiYzUxNSIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJuYW1lIjoiVGVzdCBVc2VyIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTE5NTgzOTksImV4cCI6MTc1MTk2MTk5OX0.T1iIV0VSadnAbb_Nm-okXCQ8mVd8CLrjufjx2EKFPYw
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwZDVkM2U4LTNiMTYtNDhmYS05ZTJlLTk4MzI5NDJiYzUxNSIsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJuYW1lIjoiVGVzdCBVc2VyIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NTE5NjMzMzIsImV4cCI6MTc1MTk2NDIzMn0.qtpZKSF6RsxaGqCogwPBvvFKVwVhAPanxPIqVNcV48k


### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "testuser@example.com",
    "name": "Test User",
    "password": "password123",
    "role": "USER",
    "companyId": 1
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}

### 사용자 정보 조회
GET http://localhost:8080/auth/me
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 로그아웃
POST http://localhost:8080/auth/logout
Content-Type: application/json
Cookie: accessToken={{accessToken}}
