### 회원가입
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "testuser@example.com",
    "name": "Test User",
    "password": "password123",
    "role": "USER",
    "companyId": 1
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "password123"
}