### 예산 및 지출 현황 조회
GET http://localhost:8080/admin/2/budgets

### 예산 수정(최고 관리자)
PATCH http://localhost:8080/super-admin/1/budgets
Content-Type: application/json

{
  "currentMonthBudget": 50000,
  "monthlyBudget": 900000
}