### 구매 요청 생성
POST http://localhost:8080/orders
Content-Type: application/json

{
  "userId": "user-1",
  "adminMessage": "테스트 주문",
  "requestMessage": "테스트 요청",
  "cartItemIds": [1, 2]
}

### 내 구매 요청 리스트
GET http://localhost:8080/orders
Content-Type: application/json

{
  "userId": "user-1"
}

### 구매 요청 상세 조회
GET http://localhost:8080/orders/1
Content-Type: application/json

{
  "userId": "user-1"
}

### 구매 요청 취소
PATCH http://localhost:8080/orders/1
Content-Type: application/json

{
  "userId": "user-1",
  "status": "CANCELED"
}

### 즉시 구매
POST http://localhost:8080/orders/instant
Content-Type: application/json

{
  "userId": "user-1",
  "adminMessage": "즉시 구매 테스트",
  "requestMessage": "즉시 구매 요청",
  "cartItemIds": [3]
} 