### 구매내역 조회(대기 or 승인)
GET http://localhost:8080/admin/orders?offset=0&limit=4&orderBy=latest&status=pending

### 구매내역 상세 조회(대기 or 승인)
GET http://localhost:8080/admin/orders/2?status=pending

### 구매 승인 | 구매 반려
PATCH http://localhost:8080/admin/orders/2
Content-Type: application/json

{
  "approver": "최고 관리자",
  "adminMessage": "구매 승인처리 되었습니다. 3영업일 내로 배송이 완료될 예정입니다.",
  "status": "PENDING"
}