@BASE_URL=http://localhost:8080

### 결제 테스트
POST {{BASE_URL}}/payments/confirm
Content-Type: application/json

{
  "paymentKey": "tgen_20250803201607MtVb1",
  "orderId": "eYUTmd6RKOPf9t3IeY3rX",
  "amount": "50000"
}

### 응답 테스트
GET {{BASE_URL}}/payments/test
Content-Type: application/json

{
  "orderId": "46cd5b59-d419-4140-ad13-7168e5c66037"
}