POST http://localhost:8080/products
Content-Type: multipart/form-data
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUwNWEyOTdhLTNhMjQtNGNiMS04MWIyLWVmYmUzMmEzZTRkZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNTI3NTMsImV4cCI6MTc1MjA1MzY1M30.8RkX8B2fRsa77cnZ42qUBMnF9r9JVlT6SNvVlewKXhY;

FormData:
- name: 포도
- categoryId: 28
- price: 5000
- linkUrl: https://external-shop.com/
- image: [파일 선택: grape.jpg] 


### 유저가 등록한 상품 목록
GET http://localhost:8080/my/products
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDBhMTRlLTYyNWMtNDlkOC05ZTQ3LTVmMTAzMGRkNmFiYyIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNjQ4OTQsImV4cCI6MTc1MjA2NTc5NH0.d8cNZOgcNrazWsniR88gQw8H0yomZfFqWTvbecOmhGM;

###
GET http://localhost:8080/products/5
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzM0MDUsImV4cCI6MTc1MjA3NDMwNX0.kSrVrR-c_0P4_bRB_yBq50SE0SYmZd1aN5S54e8GT74;

### 상품 전체 요청 
GET http://localhost:8080/products
Content-Type: application/json

# 쿼리스트링 옵션:
#
# - sort: 정렬 기준 (string)
#   가능한 값:
#     - latest   : 최신순 (기본값)
#     - popular  : 판매순
#     - low      : 가격 낮은순
#     - high     : 가격 높은순
#
# - category: 카테고리 ID (number)
#   예) category=3
#
# - cursor: 커서 ID (number)
#   페이징용으로 사용, 이전 요청 마지막 아이템 ID
#
# - limit: 한번에 가져올 아이템 수 (number)
#   기본값 9, 최대 50까지 허용