# 포스트맨으로 실행시켜주세요

### 로그인 (새로운 토큰 발급)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "super_admin@codeit.com",
    "password": "1q2w3e4r!"
}

### 상품 등록
POST http://localhost:8080/products
# Body
FormData:
- name: 포도
- categoryId: 28
- price: 5000
- linkUrl: https://external-shop.com/
- image: [파일 선택: grape.jpg] 


### 유저가 등록한 상품 목록
GET http://localhost:8080/my/products?orderBy=priceLow
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzU5OTUsImV4cCI6MTc1MjA3Njg5NX0.YuROnKaa9kg9X1BNCGxCb7TbJeZ_28NWoWKYpW8xAyY;

### 상품 상세 페이지
GET http://localhost:8080/products/1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzY5ODAsImV4cCI6MTc1MjA3Nzg4MH0.60Ywhc3zquw0GajtYXbXAD3k1LpT59Jx42dWPQXzd4k;

### 상품 수정
PATCH http://localhost:8080/products/8
Content-Type: application/json
Cookie:accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzM0MDUsImV4cCI6MTc1MjA3NDMwNX0.kSrVrR-c_0P4_bRB_yBq50SE0SYmZd1aN5S54e8GT74;

{
  "name": "사과",
  "price": 11000,
  "linkUrl": "https://example.com",
  "categoryId": 28
}

### 상품 수정 어드민
PATCH http://localhost:8080/admin/products/8
Content-Type: application/json
Cookie:accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzM0MDUsImV4cCI6MTc1MjA3NDMwNX0.kSrVrR-c_0P4_bRB_yBq50SE0SYmZd1aN5S54e8GT74;

{
  "name": "진라면",
  "price": "19900",
  "linkUrl": "https://google.com",
  "categoryId": "27"
}

### 상품 삭제
DELETE http://localhost:8080/products/8
Content-Type: application/json
Cookie:accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzU5MDgsImV4cCI6MTc1MjA3NjgwOH0.q5u5sUCu8QpQdzxvEKPO_4iQ8_nX-hUnYpc-Ld_xC0E;

### 상품 삭제 어드민
DELETE http://localhost:8080/admin/products/8
Content-Type: application/json
Cookie:accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OWQ0NjYwLWU5M2MtNDA1My04MjUwLWIyMzE4MThlODgzZiIsImVtYWlsIjoiYXNkMUBleGFtcGxlLmNvbSIsIm5hbWUiOiLqtIDrpqzsnpAiLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTIwNzU5MDgsImV4cCI6MTc1MjA3NjgwOH0.q5u5sUCu8QpQdzxvEKPO_4iQ8_nX-hUnYpc-Ld_xC0E;

### 카테고리
GET http://localhost:8080/products/category
Content-Type: application/json

### 상품 전체 요청 
GET http://localhost:8080/products?limit=50
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLTEiLCJlbWFpbCI6InN1cGVyX2FkbWluQGNvZGVpdC5jb20iLCJyb2xlIjoiU1VQRVJfQURNSU4iLCJpYXQiOjE3NTQwNTk2ODMsImV4cCI6MTc1NDA2MDU4M30.552pD1Oobi2XkTpszWtJjiXq06UJRNEZx3dVpu2KENU;

# 쿼리스트링 옵션:
#
# - sort: 정렬 기준 (string)
#   가능한 값:
#     - latest   : 최신순 (기본값)
#     - popular  : 판매순
#     - low      : 가격 낮은순
#     - high     : 가격 높은순
#
# - category: 카테고리 ID (number)
#   예) category=3(parentId, id)
#
# - cursor: 커서 ID (number)
#   페이징용으로 사용, 이전 요청 마지막 아이템 ID
#
# - limit: 한번에 가져올 아이템 수 (number)
#   기본값 9, 최대 50까지 허용