### 1. SUPER_ADMIN 로그인 (쿠키 획득)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "super_admin@codeit.com",
    "password": "11111111"
}

### 2. SUPER_ADMIN이 일반 유저 삭제 (성공 케이스)
DELETE http://localhost:8080/super-admin/users/user-3

### 3. SUPER_ADMIN이 관리자 삭제 (성공 케이스)
DELETE http://localhost:8080/super-admin/users/user-2

### 4. 존재하지 않는 유저 삭제 시도 (실패 케이스)
DELETE http://localhost:8080/super-admin/users/non-existent-user

### 5. SUPER_ADMIN이 자기 자신 삭제 시도 (실패 케이스)
DELETE http://localhost:8080/super-admin/users/user-1

### 6. 쿠키 없이 삭제 시도 (실패 케이스- 이거는 로컬에서 테스트 불가 - 쿠키인증 방식때문, 추후에 브라우저에서 테스트예정))
DELETE http://localhost:8080/super-admin/users/user-3

### 7. ADMIN 로그인 후 삭제 시도 (실패 케이스- (이거는 로컬에서 테스트 불가 - 쿠키인증 방식때문, 추후에 브라우저에서 테스트예정))
# @name adminLogin
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "admin@codeit.com",
    "password": "11111111"
}

### 
DELETE http://localhost:8080/super-admin/users/user-4
